### ISSUE TITLE
Header style

### ISSUE THREAD

**Issue by jananihome** [jananihome/Janani-Home#7] opened 2017-09-07 19:18 UTC
Try to have header i.e at the top like you are seeing in github. Try to bring like github black and white combo.

**Comment by mckdev** [comment] 2017-09-07 19:37
We cant really have this type of header because it takes full page width and we have a big white logo that terminates the header.

**Comment by jananihome** [comment] 2017-09-07 20:33
let me draw and send you a screen shot soon.

**Comment by mckdev** [comment] 2017-09-16 15:27
Closing because this is now a duplicate of #4

**Closed by mckdev** 2017-09-16 15:27 UTC
Labels: on hold
